using System;
using System.Collections.Generic;

#nullable disable

namespace CRM.Model
{
    public partial class Scari
    {
        public int Sfirmaid { get; set; }
        public int Crid { get; set; }
        public int? CariTip { get; set; }
        public string Crkod { get; set; }
        public string Crisim { get; set; }
        public string Cradres { get; set; }
        public string Crsehir { get; set; }
        public string Crtel { get; set; }
        public string Crtel2 { get; set; }
        public string Crgsm { get; set; }
        public string Cremail { get; set; }
        public string Cryetkili { get; set; }
        public string Crrota { get; set; }
        public string Crvergd { get; set; }
        public string Crvergno { get; set; }
        public double? Crvade { get; set; }
        public double? Crfaiz { get; set; }
        public double? Criskont { get; set; }
        public string Cristhb { get; set; }
        public double? Crrisklim { get; set; }
        public string Crurl { get; set; }
        public string Crmuhkod { get; set; }
        public string Tip { get; set; }
        public string Notlar { get; set; }
        public short? Grup { get; set; }
        public short? Produktor { get; set; }
        public short? Altacente { get; set; }
        public short? Polkomisyon { get; set; }
        public short? Tamirhane { get; set; }
        public short? Expres { get; set; }
        public short? Sigortasirket { get; set; }
        public int Usercode { get; set; }
        public DateTime? Kayitdate { get; set; }
        public int? Grupid { get; set; }
        public string Skarac { get; set; }
        public string Skkm { get; set; }
        public string Skarenk { get; set; }
        public string Sdoto { get; set; }
        public string Skaaks { get; set; }
        public string Sklup { get; set; }
        public string Sdergi { get; set; }
        public string Shobi { get; set; }
        public string Kimlikno { get; set; }
        public string Esi { get; set; }
        public DateTime? Birthdate { get; set; }
        public DateTime? Birthdateesi { get; set; }
        public short? Valor { get; set; }
        public short? Fiyat { get; set; }
        public string Crilce { get; set; }
        public short? Stokindirim { get; set; }
        public double? Iskonto { get; set; }
        public int? Scarigrupaltid { get; set; }
        public int? Sparaid { get; set; }
        public string Notlar2 { get; set; }
        public string Crpostakod { get; set; }
        public string Websifre { get; set; }
        public string Crfax { get; set; }
        public string Kod { get; set; }
        public string Unvkod { get; set; }
        public string Ayr { get; set; }
        public string Musfirkod { get; set; }
        public string Temfirkod { get; set; }
        public string Vekalet { get; set; }
        public string Kimliktip { get; set; }
        public string Imafirkod { get; set; }
        public DateTime? Gorusdate { get; set; }
        public string Notlar3 { get; set; }
        public string CrtelCopy { get; set; }
        public string Crtel2Copy { get; set; }
        public string CrgsmCopy { get; set; }
        public string Soyadi { get; set; }
        public string Crtel3 { get; set; }
        public string Crtel4 { get; set; }
        public string Crmail { get; set; }
        public string Crskype { get; set; }
        public int? Deguser { get; set; }
        public DateTime? Degdate { get; set; }
        public short? Icra { get; set; }
        public short? Avukat { get; set; }
        public DateTime? Icradate { get; set; }
        public DateTime? Avukatdate { get; set; }
        public int? Grupid2 { get; set; }
        public double? CrBorc { get; set; }
        public double? CrAlacak { get; set; }
        public DateTime? Crbirthdate { get; set; }
        public string Crsinif { get; set; }
        public DateTime? Ogrdate { get; set; }
        public float? Demirbas { get; set; }
        public short? Pasif { get; set; }
        public string Crogretmen { get; set; }
        public string KisaNot1 { get; set; }
        public string KisaNot2 { get; set; }
        public string KisaNot3 { get; set; }
        public string KAdi { get; set; }
        public string KKodu { get; set; }
        public string KTel { get; set; }
        public string KIlgili { get; set; }
        public string KNot { get; set; }
        public byte? Efatura { get; set; }
        public string Crad { get; set; }
        public string Crsoyad { get; set; }
        public string Crweb { get; set; }
        public double? Carilimit { get; set; }
        public int? Grupid4 { get; set; }
        public double? Teknikresim { get; set; }
        public double? Musterinumune { get; set; }
        public int? Teknikresimno { get; set; }
        public int? Parcaag { get; set; }
        public int? Malzeme { get; set; }
        public string Isilislemdurum { get; set; }
        public string Sertlik { get; set; }
        public string Kalibiyapanfirma { get; set; }
        public string Kalipgozad { get; set; }
        public string Parcasektor { get; set; }
        public int? Salkimparcaad { get; set; }
        public string Salkimdokumag { get; set; }
        public double? Yollukdurum { get; set; }
        public double? Yuzeykumlama { get; set; }
        public string Teslimaciklama { get; set; }
        public double? Fasonislem { get; set; }
        public double? Pasivasyon { get; set; }
        public DateTime? Numuneonaydate { get; set; }
        public double? Genelfire { get; set; }
        public double? Uretimfire { get; set; }
        public double? Toplamuretimsayi { get; set; }
        public double? Toplamuretimad { get; set; }
        public double? Fatozelkod { get; set; }
        public double? Findik { get; set; }
        public double? Sgksicilno { get; set; }
        public short? Topluft { get; set; }
        public string FtDay { get; set; }
        public short? Alici { get; set; }
        public short? Satici { get; set; }
        public DateTime? Anlasmadate { get; set; }
        public DateTime? Sozlesmebas { get; set; }
        public short? Personel { get; set; }
        public string Sex { get; set; }
        public string Boy { get; set; }
        public string Kilo { get; set; }
        public string Esneklik { get; set; }
        public string Sicrama { get; set; }
        public string Surat { get; set; }
        public string Kuvvet { get; set; }
        public short? Ticimax { get; set; }
        public short? Mailgitti { get; set; }
        public short? Yurtdisi { get; set; }
        public string Crulke { get; set; }
        public string Crulkekod { get; set; }
        public double? Pinbaccount { get; set; }
        public short? Crcountryid { get; set; }
        public short? Crcityid { get; set; }
        public short? Crstateid { get; set; }
        public short? Anabayi { get; set; }
        public short? Yetkilisatici { get; set; }
    }
}
