using System;
using System.Collections.Generic;

#nullable disable

namespace CRM.Model
{
    public partial class Sstok
    {
        public double? Sfirmaid { get; set; }
        public double Sstokid { get; set; }
        public string Stokkod { get; set; }
        public string Stokadi { get; set; }
        public string Eticaretkod { get; set; }
        public string StokadiPrknd { get; set; }
        public string Stokgrp1 { get; set; }
        public string Stokgrp2 { get; set; }
        public double? Stkdv { get; set; }
        public double? Stkdv2 { get; set; }
        public double? Stalisfiyat { get; set; }
        public byte? Kalip { get; set; }
        public double? Stsatisfiyat1 { get; set; }
        public double? Stsatisfiyat2 { get; set; }
        public double? Stkritik { get; set; }
        public string Stbirim { get; set; }
        public string Stbirim2 { get; set; }
        public double? Stbirim2katsayi { get; set; }
        public double? Stiskonto { get; set; }
        public byte? Stoto { get; set; }
        public byte? Stikinciel { get; set; }
        public string Stmarka { get; set; }
        public string Stmodel { get; set; }
        public double? Styili { get; set; }
        public string Strenk { get; set; }
        public string Staksesuar { get; set; }
        public string Stirtibat { get; set; }
        public string Stcinsi { get; set; }
        public double? Stbandrol { get; set; }
        public double? Stmotorhacim { get; set; }
        public string Stmotorno { get; set; }
        public string Stsasino { get; set; }
        public string Stagirlik { get; set; }
        public string Stistihap { get; set; }
        public string Stnot { get; set; }
        public string Stmuhkod { get; set; }
        public string Stbeygir { get; set; }
        public string Stparabirim { get; set; }
        public string Strafno { get; set; }
        public string Stsirano { get; set; }
        public double? Stx { get; set; }
        public double? Sty { get; set; }
        public double? Stz { get; set; }
        public double? Stsatisfiyat3 { get; set; }
        public double? Stsatisfiyat4 { get; set; }
        public double? Stsatisfiyat4Yedek { get; set; }
        public double? Stsatisfiyat5 { get; set; }
        public double? Stsatisfiyat6 { get; set; }
        public double? Stsatisfiyat6Yedek { get; set; }
        public double? Stkatsayi2 { get; set; }
        public short? Stotv { get; set; }
        public string Stsilindir3 { get; set; }
        public string Stsilindir { get; set; }
        public string Oturma { get; set; }
        public string Stokturu { get; set; }
        public short? Stokturkod { get; set; }
        public string Stbirim3 { get; set; }
        public double? Stbirim3katsayi { get; set; }
        public string Stokgrp3 { get; set; }
        public string Barcode { get; set; }
        public long? Barcode9 { get; set; }
        public short? Grupmu { get; set; }
        public double? Acilismiktari { get; set; }
        public short? Pasif { get; set; }
        public short? Demirbas { get; set; }
        public string Beden { get; set; }
        public double? Oran { get; set; }
        public double? Giris { get; set; }
        public double? Cikis { get; set; }
        public double? Sfirmaidtemp { get; set; }
        public double? Stalisfiyattemp { get; set; }
        public double? Stokadet { get; set; }
        public double? Malzeme { get; set; }
        public string Stokgrp4 { get; set; }
        public string Stokgrp5 { get; set; }
        public string Stokgrp6 { get; set; }
        public short? Hizlisatis { get; set; }
        public short? PktBol { get; set; }
        public double? Stsatisfiyat7 { get; set; }
        public DateTime? Gecerliliktrh { get; set; }
        public string SiparisAdedi { get; set; }
        public double? Teknikresim { get; set; }
        public short? Musterinumune { get; set; }
        public string Teknikresimno { get; set; }
        public double? Kalipgozad { get; set; }
        public double? Parcaag { get; set; }
        public double? Genelmalzeme { get; set; }
        public string Isilislemdurum { get; set; }
        public string Sertlik { get; set; }
        public string Kalibiyapanfirma { get; set; }
        public double? Salkimparcaad { get; set; }
        public double? Salkimdokumag { get; set; }
        public double? Yollukdurumu { get; set; }
        public double? Scariid { get; set; }
        public double? Yuzeykumlama { get; set; }
        public string Teslimaciklama { get; set; }
        public double? Fasonislem { get; set; }
        public double? Pasivasyon { get; set; }
        public DateTime? Numuneonaydate { get; set; }
        public double? Genelfire { get; set; }
        public double? Uretimfire { get; set; }
        public double? Toplamuretimsayisi { get; set; }
        public double? Toplamuretimad { get; set; }
        public double? Uststokid { get; set; }
        public double? Enustid { get; set; }
        public double? Enjfire { get; set; }
        public double? Seramikfire { get; set; }
        public double? Baskisuresi { get; set; }
        public double? Parcadokumag { get; set; }
        public short? Sifirlama { get; set; }
        public short? Zimpara { get; set; }
        public short? Isilislem { get; set; }
        public double? Filtreid { get; set; }
        public double? Parcadokumad { get; set; }
        public double? Gerceklesenfire { get; set; }
        public string Caritur { get; set; }
        public DateTime? Kayittarihi { get; set; }
        public short? Islemturu { get; set; }
        public double? Deguser { get; set; }
        public DateTime? Degdate { get; set; }
        public short? Stdoviz1 { get; set; }
        public short? Stdoviz2 { get; set; }
        public short? Stdoviz3 { get; set; }
        public double? Maliyethesaplanan { get; set; }
        public double? Maliyeturetim { get; set; }
        public string Caritur2 { get; set; }
        public string Baglamakodu { get; set; }
        public double? Eticaretgrup1 { get; set; }
        public double? Eticaretgrup2 { get; set; }
        public double? Eticaretgrup3 { get; set; }
        public double? Eticaretgrup4 { get; set; }
        public double? Color1 { get; set; }
        public double? Color2 { get; set; }
        public double? Color3 { get; set; }
        public double? Blocksizeid { get; set; }
        public double? Genelsizeid { get; set; }
        public string Lotno { get; set; }
        public double? Modelid { get; set; }
        public double? Qualityid { get; set; }
        public double? Materialid { get; set; }
        public double? Yapiid { get; set; }
        public double? Designind { get; set; }
        public double? Scaleid { get; set; }
        public string Tahminiolcu1 { get; set; }
        public string Tahminiolcu2 { get; set; }
        public string Tahminiolcu3 { get; set; }
        public string Tahminiolcu4 { get; set; }
        public double? Backingid { get; set; }
        public DateTime? Kayitdate { get; set; }
        public double? Kayituser { get; set; }
        public double? Sonisemri { get; set; }
        public double? Salkimmumag { get; set; }
        public string Yollukad { get; set; }
        public DateTime? Parcakayittar { get; set; }
        public string Fasonaciklama { get; set; }
        public string Sifirlamaaciklama { get; set; }
        public string Zimparaaciklama { get; set; }
        public string Isilislemaciklama { get; set; }
        public string Kritikolculer { get; set; }
        public short? Karaliste { get; set; }
        public string Karalistesebep { get; set; }
        public string Kaynakmlz { get; set; }
        public double? Sarfkodu { get; set; }
        public string Gtip { get; set; }
        public string StokadiEn { get; set; }
        public string StokadiFr { get; set; }
        public string Taahhutname { get; set; }
        public string Article { get; set; }
        public double? Stsatisfiyat8 { get; set; }
        public double? Stsatisfiyat9 { get; set; }
        public double? Pinbaccount { get; set; }
        public int? Icambalaj { get; set; }
        public int? Disambalaj { get; set; }
        public int? Ekambalaj { get; set; }
        public double? Netagirlikkg { get; set; }
        public int? KoliTipi { get; set; }
        public string UnTipi { get; set; }
        public short? Recetesiz { get; set; }
        public short? Cozelti { get; set; }
        public string Berabertasima { get; set; }
        public short? Maddehali { get; set; }
        public double? SertifikaId { get; set; }
        public string Kalipyeri { get; set; }
        public short? Webdegoster { get; set; }
        public short? Yeni { get; set; }
        public double? Stsatisfiyat10 { get; set; }
        public double? Sonfireorani { get; set; }
        public string StokadiFatura { get; set; }
        public short? Teklif { get; set; }
        public double? Dokumsicakligi { get; set; }
        public double? Firinsicakligi { get; set; }
        public string Parcasektor { get; set; }
    }
}
